#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe GridsController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # Grid. As you add validations to Grid, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    {}
#  end
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # GridsController. Be sure to keep this updated too.
#  def valid_session
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all grids as @grids" do
#      grid = Grid.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:grids).should eq([grid])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested grid as @grid" do
#      grid = Grid.create! valid_attributes
#      get :show, {:id => grid.to_param}, valid_session
#      assigns(:grid).should eq(grid)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new grid as @grid" do
#      get :new, {}, valid_session
#      assigns(:grid).should be_a_new(Grid)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested grid as @grid" do
#      grid = Grid.create! valid_attributes
#      get :edit, {:id => grid.to_param}, valid_session
#      assigns(:grid).should eq(grid)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new Grid" do
#        expect {
#          post :create, {:grid => valid_attributes}, valid_session
#        }.to change(Grid, :count).by(1)
#      end
#
#      it "assigns a newly created grid as @grid" do
#        post :create, {:grid => valid_attributes}, valid_session
#        assigns(:grid).should be_a(Grid)
#        assigns(:grid).should be_persisted
#      end
#
#      it "redirects to the created grid" do
#        post :create, {:grid => valid_attributes}, valid_session
#        response.should redirect_to(Grid.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved grid as @grid" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Grid.any_instance.stub(:save).and_return(false)
#        post :create, {:grid => {}}, valid_session
#        assigns(:grid).should be_a_new(Grid)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Grid.any_instance.stub(:save).and_return(false)
#        post :create, {:grid => {}}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested grid" do
#        grid = Grid.create! valid_attributes
#        # Assuming there are no other grids in the database, this
#        # specifies that the Grid created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        Grid.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, {:id => grid.to_param, :grid => {'these' => 'params'}}, valid_session
#      end
#
#      it "assigns the requested grid as @grid" do
#        grid = Grid.create! valid_attributes
#        put :update, {:id => grid.to_param, :grid => valid_attributes}, valid_session
#        assigns(:grid).should eq(grid)
#      end
#
#      it "redirects to the grid" do
#        grid = Grid.create! valid_attributes
#        put :update, {:id => grid.to_param, :grid => valid_attributes}, valid_session
#        response.should redirect_to(grid)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the grid as @grid" do
#        grid = Grid.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Grid.any_instance.stub(:save).and_return(false)
#        put :update, {:id => grid.to_param, :grid => {}}, valid_session
#        assigns(:grid).should eq(grid)
#      end
#
#      it "re-renders the 'edit' template" do
#        grid = Grid.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Grid.any_instance.stub(:save).and_return(false)
#        put :update, {:id => grid.to_param, :grid => {}}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested grid" do
#      grid = Grid.create! valid_attributes
#      expect {
#        delete :destroy, {:id => grid.to_param}, valid_session
#      }.to change(Grid, :count).by(-1)
#    end
#
#    it "redirects to the grids list" do
#      grid = Grid.create! valid_attributes
#      delete :destroy, {:id => grid.to_param}, valid_session
#      response.should redirect_to(grids_url)
#    end
#  end
#
#end
